### ISSUE TITLE
Question about the coopnet network

### ISSUE THREAD

**Issue by gaozhiguang** [skgabriel/coopnet#1]
Hi, skgabrie, this work is nice, but i have a question, how does the generator cooperate with the discriminator, as i know, the discriminator and generator are separate. In other words, the discriminator just selects the best one from the candidate digest set generated by the generator,  the discriminator does not affect the generator to generate the summary, the quality of the generated summary depends only on the generator.
I don't know exactly. Maybe I made a mistake, i don't see the loss of discriminator would affect the geneator

**Comment by skgabriel** [comment]
Hi, the "cooperative" part only takes place during inference time when we use a combination of both the discriminator and generator scores to decide on the final candidate summary. As you said, the discriminator and generator are separate, which allows for different models and objectives to be combined during inference without the need for retraining.
