### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by FYYFU** [skgabriel/coopnet#2]
Hi!    In the paper, the  Equal 9 show how to calculate the final score, I wonder if the discriminator only used for modifing the final scores, rather than to improve the generator ? 
The generator and discriminator seems trained seperately, and there is no adversarial training in the code ?

**Comment by FYYFU** [comment]
> Hi! In the paper, the Equal 9 show how to calculate the final score, I wonder if the discriminator only used for modifing the final scores, rather than to improve the generator ?
> The generator and discriminator seems trained seperately, and there is no adversarial training in the code ?

Sorry... I didn't notice the issue1. But I Still wonder if it can be called discriminator. It might should be called a scorer?   :eyes:

**Comment by skgabriel** [comment]
Hi! The discriminator model is doing reranking after generation (there's no connection to the generator during training). We call it a discriminator because it is doing discriminative rather than generative modeling.

**Comment by skgabriel** [comment]
This allows us to take advantage of bidirectional sequence information when selecting the best generation and try different reranking schemes (:
